version: "3.9"

services:
  # Main API Gateway
  api-gateway:
    build: .
    container_name: ai-api-gateway
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - YOLO_SERVICE_URL=http://yolo-service:8100
      - LLM_SERVICE_URL=http://llm-service:8200
    depends_on:
      - yolo-service
      - llm-service
    restart: unless-stopped
    networks:
      - ai-network

  # YOLO Object Detection Service (for face and location masking)
  yolo-service:
    build:
      context: ./services/yolo
      dockerfile: Dockerfile
    container_name: yolo-service
    ports:
      - "8100:8100"
    volumes:
      - ./services/yolo/models:/app/models
    restart: unless-stopped
    networks:
      - ai-network

  # LLM Service (for PII detection)
  llm-service:
    build:
      context: ./services/llm
      dockerfile: Dockerfile
    container_name: llm-service
    ports:
      - "8200:8200"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped
    networks:
      - ai-network

networks:
  ai-network:
    driver: bridge