version: "3.9"

services:
  # Main API Gateway
  api-gateway:
    build: .
    container_name: ai-api-gateway
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - YOLO_SERVICE_URL=http://yolo-service:8100
      - LLM_SERVICE_URL=http://llm-service:8200
      - LOCATION_SERVICE_URL=http://location-service:8300
    depends_on:
      - yolo-service
      - llm-service
      - location-service
    restart: unless-stopped
    networks:
      - ai-network

  yolo-service:
    build:
      context: ./services/yolo
      dockerfile: Dockerfile
    container_name: yolo-service
    ports:
      - "8100:8100"
    volumes:
      - ./services/yolo/models:/app/models
    restart: unless-stopped
    networks:
      - ai-network

  llm-service:
    build:
      context: ./services/llm
      dockerfile: Dockerfile
    container_name: llm-service
    ports:
      - "8200:8200"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped
    networks:
      - ai-network
  
  location-service:
    build:
      context: ./services/location
      dockerfile: Dockerfile
    container_name: location-service
    ports:
      - "8300:8300"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    restart: unless-stopped
    networks:
      - ai-network

networks:
  ai-network:
    driver: bridge