version: "3.9"

services:
  # Main API Gateway
  api-gateway:
    build: .
    container_name: ai-api-gateway
    ports:
      - "5000:5000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - YOLO_SERVICE_URL=http://yolo-service:7000
      - OPENAI_SERVICE_URL=http://openai-service:9000
    depends_on:
      - yolo-service
      - openai-service
    restart: unless-stopped
    networks:
      - ai-network

  # YOLO Object Detection Service (for face and location masking)
  yolo-service:
    build:
      context: ./src/services/yolo
      dockerfile: Dockerfile.yolo
    container_name: yolo-service
    ports:
      - "7000:7000"
    volumes:
      - ./models:/app/models
    restart: unless-stopped
    networks:
      - ai-network

  # OpenAI Service (for chat and PII detection)
  openai-service:
    build:
      context: ./src/services/openai
      dockerfile: Dockerfile.openai
    container_name: openai-service
    ports:
      - "9000:9000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped
    networks:
      - ai-network

  # Age Detection Service (for minor protection with YOLO + age models)
  age-detection-service:
    build:
      context: ./src/services/age
      dockerfile: Dockerfile
    container_name: age-detection-service
    ports:
      - "5100:5100"
    volumes:
      - ./models:/app/models
    restart: unless-stopped
    networks:
      - ai-network

networks:
  ai-network:
    driver: bridge

volumes:
  models: